services:
  - type: web
    name: flask-football-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install numpy==1.21.0 pandas==1.3.3
      pip install -r requirements.txt
    startCommand: python fetch_data.py
    envVars:
      - key: DATABASE_URL
        value: <your_database_url>
      - key: API_KEY
        value: <your_api_key>
      - key: API_HOST
        value: <your_api_host>
