services:
  - type: web
    name: flask-football-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential gcc gfortran libblas-dev liblapack-dev
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: python fetch_data.py
    envVars:
      - key: DATABASE_URL
        value: <your_database_url>
      - key: API_KEY
        value: <your_api_key>
      - key: API_HOST
        value: <your_api_host>
